version: '3'
services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    volumes:
      - ./fastapi:/src
      - ./.env:/src/.env
    depends_on:
      - redis 
  redis:
    image: redis:alpine
    ports:
      - 6379:6379 # ${REDIS_BINDING_PORT}:${REDIS_PORT}
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/newmantle.conf:/etc/nginx/conf.d/newmantle.conf
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"