version: '3'
services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    volumes:
      - ./fastapi:/src
      - ./.env:/src/.env
    command: ["--workers", "2"]
    depends_on:
      - redis 
  redis:
    image: redis:alpine
    ports:
      - 6379:6379 # ${REDIS_BINDING_PORT}:${REDIS_PORT}
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/nginx-reload.sh:/nginx-reload.sh
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet --deploy-hook \"/nginx-reload.sh\"; sleep 24h; done'"
    depends_on:
      - nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/newmantle.conf:/etc/nginx/conf.d/newmantle.conf