version: '3'
services:
  fastapi-test:
    build:
      context: ./fastapi
      target: test
    volumes:
      - ./fastapi:/src
      - ./.env:/src/.env
    depends_on:
      - redis-test
      - postgres-test
  postgres-test:
    image: postgres:alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
  redis-test:
    image: redis:alpine
